version: 2.0
 jobs: 
  build: 
   docker:

      - image: alpine:3.7
    steps:
      - run:
          name: 最初のステップ
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline
