version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2

      - image: alpine:3.7
    steps:
      - run:
          name: 最初のステップ
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
